### ISSUE TITLE
Value '1' has no effect for boolean API GET parameters 

### ISSUE THREAD

**Issue by jojoob** [Opencast-Moodle/moodle-repository_opencast#22]
On [line 302 in lib.php](https://github.com/Opencast-Moodle/moodle-repository_opencast/blob/c0dc6a938b4ba7c7edf9a7a16549747ebec593f4/lib.php#L302) the boolean parameters `sign`, `withmetadata` and `withpublications` are set to '1'. This has no effect, at least with Opencast 11.8.

```php
$query = '/api/events?sign=1&withmetadata=1&withpublications=1&filter=' . urlencode($seriesfilter);
```

Changing the parameter values to `true` works. But with `withmetadata=true` the request takes much longer (about 4 times longer) to complete on my test instance.

Beside the faulty code I noticed no (visible) bugs caused by it.

**Comment by justusdieckmann** [comment]
Thank you very much for this issue!

It doesn't really cause bugs, but I guess they saw that it doesn't add the publications, and so they pulled the publications for every video separately. #26 fixes and removes that.

Cheers
Justus
